server:
  port: 8688
  servlet:
    contextPath: /api

spring:
  datasource: #jdbc:sqlite://Users/onggowahyudi/nus/task-tracker-api/database.db
    url: jdbc:sqlite:/Users/brittaalex/Documents/workstation/mtech-worskpace/task-tracker-api/db/tasktracker
    driver-class-name: org.sqlite.JDBC
    username:
    password:
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  devtools:
    restart:
      enabled: true


